export const universityItems = [
  {
    rank: 1,
    slug: "massachusetts-institute-of-technology",
    image: "/universitiesimages/MIT.jpg",
    logo: "/universityeslogos/mitlogo.png",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, Massachusetts, USA",
    desc: "Massachusetts Institute of Technology (MIT), founded in 1861 in Cambridge, Massachusetts, is a world-leading institution, renowned for innovation, science, engineering, technology, entrepreneurship, groundbreaking research, and globally influential alumni.",
    students: "501",
    acceptance: "4%",
  },
  {
    rank: 2,
    slug: "harvard-university",
    image: "/universitiesimages/harwarduniversity.jpg",
    logo: "/universityeslogos/harvarduniversity.png",
    name: "Harvard University",
    location: "Cambridge, Massachusetts",
    desc: "Harvard University, founded in 1636 in Cambridge, Massachusetts, is the oldest Ivy League institution, globally renowned for academic excellence, research, leadership, professional schools, vast libraries, distinguished alumni, and worldwide influence.",
    students: "24,519",
    acceptance: "3.5%",
  },
  {
    rank: 3,
    slug: "stanford-university",
    image: "/universitiesimages/stanforduniversity.jpg",
    logo: "/universityeslogos/stanforduniversity.png",
    name: "Stanford University",
    location: "Stanford, California, USA",
    desc: "Stanford University, founded in 1885 in Stanford, California, is a world-renowned institution recognized for academic excellence, research, innovation, entrepreneurship, strong Silicon Valley ties, diverse programs, and influential global alumni.",
    students: "27,529",
    acceptance: "3.9%",
  },
  {
    rank: 4,
    slug: "princeton-university",
    image: "/universitiesimages/princetonuniversity.jpg",
    logo: "/universityeslogos/princetonuniversity.png",
    name: "Princeton University",
    location: "Princeton, New Jersey",
    desc: "Princeton University, founded in 1746 in Princeton, New Jersey, is a prestigious Ivy League institution known for academic excellence, cutting-edge research, liberal arts focus, distinguished faculty, historic campus, and influential alumni.",
    students: "5,709",
    acceptance: "4.5%",
  },
  {
    rank: 5,
    slug: "university-of-cambridge",
    image: "/universitiesimages/universityofcambridge.jpg",
    logo: "/universityeslogos/universityofcambridge.png",
    name: "University of Cambridge",
    location: "Cambridge, Cambridgeshire",
    desc: "The University of Cambridge, founded in 1209 in Cambridge, England, is a world-leading institution renowned for academic excellence, research, historic colleges, Nobel laureates, influential alumni, and global contributions to knowledge.",
    students: "21,175",
    acceptance: "21%",
  },
  {
    rank: 6,
    slug: "california-institute-of-technology",
    image: "/universitiesimages/UniversityofCaltech.jpg",
    logo: "/universityeslogos/universityofcaltech.png",
    name: "University of Caltech",
    location: "Pasadena, California",
    desc: "The California Institute of Technology (Caltech), founded in 1891 in Pasadena, California, is a world-renowned institution focused on science, engineering, research, innovation, small student-faculty ratio, and producing influential global leaders.",
    students: "1,443",
    acceptance: "3.1%",
  },
  {
    rank: 7,
    slug: "yale-university",
    image: "/universitiesimages/YaleUniversity.png",
    logo: "/universityeslogos/yaleuniversity.png",
    name: "Yale University",
    location: "New Haven, Connecticut",
    desc: "Yale University, founded in 1701 in New Haven, Connecticut, is a prestigious Ivy League institution, renowned for academic excellence, research, liberal arts education, residential college system, and globally influential alumni.",
    students: "15000",
    acceptance: "4.5%",
  },
  {
    rank: 8,
    slug: "national-university-of-singapore",
    image: "/universitiesimages/NationalUniversityofSingapore.jpeg",
    logo: "/universityeslogos/nationaluniversityofsingapore.png",
    name: "National University of Singapore",
    location: "Singapore",
    desc: "The National University of Singapore (NUS) is Singapore’s oldest and largest university, established in 1905. It is globally recognized for research excellence and top academic programs across various fields. NUS attracts a diverse international student body and drives innovation and entrepreneurship in Singapore.",
    students: "38,000+",
    acceptance: "30%",
  },
  {
    rank: 9,
    slug: "imperial-college-london",
    image: "/universitiesimages/ImperialCollegeLondon.jpeg",
    logo: "/universityeslogos/imperialcollegelondon.png",
    name: "Imperial College London",
    location: "London, England,",
    desc: "Imperial College London, located in the heart of London, is a world-leading university specializing in science, engineering, medicine, and business. It is renowned for its cutting-edge research, innovation, and strong industry connections.",
    students: "22,000",
    acceptance: "16%",
  },
  {
    rank: 10,
    slug: "university-of-california-berkeley",
    image: "/universitiesimages/UniversityofCaliforniaBerkeley.jpeg",
    logo: "/universityeslogos/universityofcaliforniaberkeley.png",
    name: "University of California, Berkeley ",
    location: "Berkeley, California",
    desc: "The University of California, Berkeley, is a top-ranked public research university known for academic excellence and innovation. It offers diverse programs and a vibrant campus culture that fosters leadership and groundbreaking research.",
    students: "12,914",
    acceptance: "11.7%",
  },
];
