export const universityItems = [
  {
    id: 1,
    rank: 1,
    slug: "massachusetts-institute-of-technology",
    name: "Massachusetts Institute of Technology (MIT)",
    country: "USA",
    location: "Cambridge, Massachusetts, USA",
    flag: "🇺🇸",
    degree: "Masters / PhD",
    tuition: "$60,000 – $82,000 / year",
    ranking: "QS World #1 (2026)",
    logo: "/universityeslogos/mitlogo.png",
    image: "/universitiesimages/MIT.jpg",
    students: "11,800",
    acceptanceRate: "4%",
    desc: "The Massachusetts Institute of Technology (MIT) is a world-leading private research university located in Cambridge, Massachusetts, United States, renowned globally for its unparalleled excellence in innovation, engineering, technology, entrepreneurship, and groundbreaking research. Founded in 1861 by William Barton Rogers in response to the rapid industrialization of America, MIT was established with a visionary mission: to advance knowledge and educate students in science, technology, and other areas of scholarship that will best serve the nation and the world in the 21st century.",
  },

  {
    id: 2,
    rank: 2,
    slug: "imperial-college-london",
    name: "Imperial College London",
    country: "United Kingdom",
    location: "London, England",
    flag: "🇬🇧",
    degree: "Masters",
    tuition: "£36,000 – £48,000 / year",
    ranking: "QS World #2 (2026)",
    logo: "/universityeslogos/imperialcollegelondon.png",
    image: "/universitiesimages/ImperialCollegeLondon.jpeg",
    students: "22,000",
    acceptanceRate: "16%",
    desc: "Imperial College London is a top global university specializing in science, engineering, medicine, and business, consistently ranked among the world's elite institutions for its relentless focus on research-led education, practical innovation, and real-world impact.Founded in 1907 by royal charter under the vision of Prince Albert (inspired by the Great Exhibition of 1851), Imperial was created by uniting historic institutions: the Royal College of Science, the Royal School of Mines, and the City and Guilds of London Institute.",
  },

  {
    id: 3,
    rank: 3,
    slug: "stanford-university",
    name: "Stanford University",
    country: "USA",
    location: "Stanford, California, USA",
    flag: "🇺🇸",
    degree: "Masters",
    tuition: "$62,000 – $80,000 / year",
    ranking: "QS World #3 (2026)",
    logo: "/universityeslogos/stanforduniversity.png",
    image: "/universitiesimages/stanforduniversity.jpg",
    students: "27,500",
    acceptanceRate: "3.9%",
    desc: "Stanford University is globally renowned for innovation, entrepreneurship, research excellence, and its unparalleled Silicon Valley connections, making it one of the world's most influential and transformative institutions.Founded in 1885 by railroad magnate Leland Stanford and his wife Jane in memory of their late son, the university opened its doors in 1891 with a bold mission: to produce well-rounded graduates equipped to contribute to society through practical, impactful education.",
  },

  {
    id: 4,
    rank: 4,
    slug: "harvard-university",
    name: "Harvard University",
    country: "USA",
    location: "Cambridge, Massachusetts, USA",
    flag: "🇺🇸",
    degree: "Masters / PhD",
    tuition: "$55,000 – $75,000 / year",
    ranking: "QS World Top 5 (2026)",
    logo: "/universityeslogos/harvarduniversity.png",
    image: "/universitiesimages/harwarduniversity.jpg",
    students: "24,500",
    acceptanceRate: "3.5%",
    desc: "Harvard University is the oldest university in the United States, globally known for its unparalleled academic excellence, leadership in education and research, and its profound influence on shaping world leaders, innovators, and thinkers across centuries. Founded in 1636 in Cambridge, Massachusetts, by vote of the Massachusetts Bay Colony's Great and General Court, Harvard was initially established to train Puritan clergy and educate the colony's future leaders.",
  },

  {
    id: 5,
    rank: 5,
    slug: "university-of-cambridge",
    name: "University of Cambridge",
    country: "United Kingdom",
    location: "Cambridge, England",
    flag: "🇬🇧",
    degree: "Bachelors / Masters",
    tuition: "£25,000 – £45,000 / year",
    ranking: "QS World Top 5 (2026)",
    logo: "/universityeslogos/universityofcambridge.png",
    image: "/universitiesimages/universityofcambridge.jpg",
    students: "21,000",
    acceptanceRate: "21%",
    desc: "The University of Cambridge is one of the world’s oldest and most prestigious institutions, renowned for its profound research impact, academic excellence, and centuries-long tradition of fostering intellectual rigor, innovation, and transformative discovery. Founded in 1209 by scholars fleeing disputes at the University of Oxford, Cambridge is the second-oldest university in the English-speaking world and has operated continuously for over eight centuries.",
  },

  {
    id: 6,
    rank: 6,
    slug: "university-of-oxford",
    name: "University of Oxford",
    country: "United Kingdom",
    location: "Oxford, England",
    flag: "🇬🇧",
    degree: "Masters / PhD",
    tuition: "£28,000 – £50,000 / year",
    ranking: "QS World Top 5 (2026)",
    logo: "/universityeslogos/oxfordlogo.png",
    image: "/universitiesimages/oxforduniversity.jpg",
    students: "24,000",
    acceptanceRate: "17%",
    desc: "The University of Oxford is a world-leading institution known for its unparalleled research excellence, rich history, and immense global influence, standing as one of the most ancient and prestigious universities in the world. Evidence of teaching dates back to 1096, making it the oldest university in the English-speaking world, with organized colleges emerging in the 13th century. Oxford's enduring legacy lies in its tutorial-based education system, where students receive personalized, intensive supervision from leading scholars in small groups or one-on-one sessions, fostering deep critical thinking, debate, and intellectual independence.",
  },

  {
    id: 8,
    rank: 8,
    slug: "national-university-of-singapore",
    name: "National University of Singapore",
    country: "Singapore",
    location: "Singapore",
    flag: "🇸🇬",
    degree: "Bachelors / Masters",
    tuition: "$17,000 – $38,000 / year",
    ranking: "QS World Top 30 (2026)",
    logo: "/universityeslogos/nationaluniversityofsingapore.png",
    image: "/universitiesimages/NationalUniversityofSingapore.jpeg",
    students: "38,000+",
    acceptanceRate: "30%",
    desc: "The National University of Singapore (NUS) is Asia’s top university, globally recognized for its exceptional research, innovation, and academic excellence, serving as Singapore's flagship institution and a leading force in higher education across the continent and beyond. Established in its current form in 1980 through the merger of the University of Singapore and Nanyang University (with roots tracing back to 1905 as the Straits Settlements and Federated Malay States Government Medical School), NUS embodies a forward-looking vision: to educate, inspire, and transform through a global approach to education and research, with a distinctive Asian perspective and expertise.",
  },

  //9

  {
    id: 17,
    rank: 9,
    slug: "university-college-london",
    name: "University College London (UCL)",
    country: "United Kingdom",
    location: "London",
    flag: "🇬🇧",
    degree: "Bachelors / Masters / PhD",
    tuition: "$35,000 – $55,000 / year",
    ranking: "QS World #9 (2026)",
    logo: "/universityeslogos/ucllogo.jpg",
    image: "/universitiesimages/ucl.jpg",
    students: "42,000+",
    acceptanceRate: "~30-40%",
    desc: "UCL is a multidisciplinary university excelling in medicine, social sciences, engineering, and arts. Centrally located in London, it promotes global perspectives, diverse research, and impactful real-world applications.",
  },

  //10

  {
    id: 14,
    rank: 10,
    slug: "university-of-california-berkeley",
    name: "University of California, Berkeley",
    country: "USA",
    location: "Berkeley, California, USA",
    flag: "🇺🇸",
    degree: "Masters",
    tuition: "$44,000 – $58,000 / year",
    ranking: "QS World Top 50 (2026)",
    logo: "/universityeslogos/universityofcaliforniaberkeley.png",
    image: "/universitiesimages/UniversityofCaliforniaBerkeley.jpeg",
    students: "45,000+",
    acceptanceRate: "11.7%",
    desc: "The University of California, Berkeley (UC Berkeley) is a top public research university globally known for its pioneering innovation, vibrant activism, and exceptional academic excellence, serving as a beacon of progressive thought, groundbreaking discovery, and social impact in the heart of the San Francisco Bay Area. Founded in 1868 as the first campus of the University of California system and named after the philosopher George Berkeley, it emerged as a land-grant institution dedicated to public education, practical knowledge, and advancing human welfare. From its early days, UC Berkeley has embodied the spirit of 'public good' blending rigorous scholarship with a commitment to free speech, civil rights, and societal change—most famously through the Free Speech Movement of the 1960s, which galvanized student activism worldwide and cemented its reputation as a cradle of progressive politics and social justice.",
  },

  {
    id: 11,
    rank: 50,
    slug: "technical-university-of-munich",
    name: "Technical University of Munich",
    country: "Germany",
    location: "Munich, Germany",
    flag: "🇩🇪",
    degree: "Masters",
    tuition: "€0 – €6,000 / year",
    ranking: "QS World #50 (2026)",
    logo: "/universityeslogos/tum.png",
    image: "/universitiesimages/technicaluniversityofmunich.jpg",
    students: "48,000+",
    acceptanceRate: "8%",
    desc: "TUM is Germany’s leading technical university, offering high-quality education with minimal tuition fees.",
  },

  {
    id: 12,
    rank: 18,
    slug: "eth-zurich",
    name: "ETH Zurich",
    country: "Switzerland",
    location: "Zurich, Switzerland",
    flag: "🇨🇭",
    degree: "Masters / PhD",
    tuition: "CHF 1,500 / year",
    ranking: "QS World Top 20 (2026)",
    logo: "/universityeslogos/ethzurich.png",
    image: "/universitiesimages/ethzurich.jpg",
    students: "22,000",
    acceptanceRate: "27%",
    desc: "ETH Zurich is a world-class technical university known for engineering, science, and research excellence.",
  },

  {
    id: 13,
    rank: 20,
    slug: "university-of-sydney",
    name: "University of Sydney",
    country: "Australia",
    location: "Sydney, Australia",
    flag: "🇦🇺",
    degree: "Bachelors / Masters",
    tuition: "$31,000 – $56,000 / year",
    ranking: "QS World Top 20 (2026)",
    logo: "/universityeslogos/sydney.png",
    image: "/universitiesimages/sydney.jpg",
    students: "73,000+",
    acceptanceRate: "30%",
    desc: "University of Sydney is Australia’s oldest university with strong academic reputation and global rankings.",
  },

  {
    id: 10,
    rank: 40,
    slug: "university-of-british-columbia",
    name: "University of British Columbia",
    country: "Canada",
    location: "Vancouver, Canada",
    flag: "🇨🇦",
    degree: "Bachelors / Masters",
    tuition: "$32,000 – $52,000 / year",
    ranking: "QS World Top 40 (2026)",
    logo: "/universityeslogos/ubc.png",
    image: "/universitiesimages/ubc.jpg",
    students: "66,000+",
    acceptanceRate: "52%",
    desc: "The University of British Columbia (UBC) is a top public university in Canada, renowned for its research excellence and stunningly beautiful campuses that blend natural splendor with world-class academic facilities. Established in 1908 and opening its doors in 1915, UBC has grown into one of Canada's leading research-intensive institutions, with a mission to pursue excellence in research, learning, and engagement to foster global citizenship and advance a sustainable, just society across British Columbia, Canada, and the world. Its two primary campuses—Vancouver and Okanagan—offer distinct yet complementary experiences: the flagship Vancouver campus perched on the scenic Point Grey Peninsula overlooking the Pacific Ocean, with snow-capped mountains, forests, and ocean views creating one of the most picturesque university settings globally, and the Okanagan campus in Kelowna, nestled in the heart of British Columbia's wine country amid lakes, vineyards, and mountains, providing a more intimate, innovative community vibe.",
  },

  {
    id: 15,
    rank: 47,
    slug: "university-of-tokyo",
    name: "University of Tokyo",
    country: "Japan",
    location: "Tokyo, Japan",
    flag: "🇯🇵",
    degree: "Masters / PhD",
    tuition: "$5,000 – $7,000 / year",
    ranking: "QS World Top 50 (2026)",
    logo: "/universityeslogos/universityoftokyo.png",
    image: "/universitiesimages/universityoftokyo.jpg",
    students: "28,000+",
    acceptanceRate: "34%",
    desc: "The University of Tokyo is Japan’s leading university, known for research excellence and strong global rankings.",
  },

  {
    id: 7,
    rank: 21,
    slug: "university-of-toronto",
    name: "University of Toronto",
    country: "Canada",
    location: "Toronto, Ontario, Canada",
    flag: "🇨🇦",
    degree: "Masters",
    tuition: "$28,000 – $48,000 / year",
    ranking: "QS World #21 (2026)",
    logo: "/universityeslogos/universityoftoronto.png",
    image: "/universitiesimages/universityoftoronto.jpg",
    students: "74,000+",
    acceptanceRate: "43%",
    desc: "The University of Oxford is a world-leading institution known for its unparalleled research excellence, rich history, and immense global influence, standing as one of the most ancient and prestigious universities in the world. Evidence of teaching dates back to 1096, making it the oldest university in the English-speaking world, with organized colleges emerging in the 13th century. Oxford's enduring legacy lies in its tutorial-based education system, where students receive personalized, intensive supervision from leading scholars in small groups or one-on-one sessions, fostering deep critical thinking, debate, and intellectual independence.",
  },
  {
    id: 9,
    rank: 33,
    slug: "university-of-melbourne",
    name: "University of Melbourne",
    country: "Australia",
    location: "Melbourne, Australia",
    flag: "🇦🇺",
    degree: "Bachelors / Masters",
    tuition: "$30,000 – $52,000 / year",
    ranking: "QS World #33 (2026)",
    logo: "/universityeslogos/melbourne.png",
    image: "/universitiesimages/universityofmelbourne.jpg",
    students: "52,000+",
    acceptanceRate: "70%",
    desc: "The University of Melbourne is one of Australia’s top institutions, with exceptional employability outcomes and a formidable global reputation as a leading public research university. Founded in 1853, it is Australia's second-oldest university (after the University of Sydney) and has long been regarded as the nation's premier institution for academic rigor, research impact, and producing highly sought-after graduates who excel in diverse fields worldwide. Located primarily on its historic Parkville campus in the vibrant city of Melbourne—often ranked among the world's most livable cities—the university blends Gothic Revival architecture with state-of-the-art facilities, creating an inspiring environment for intellectual growth and innovation.",
  },
];
